# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mysqldb
    image: mysql
    restart: always
    env_file:
      - .env
    # (this is just an example, not intended to be a production configuration)
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldata: